language: d
sudo: false

matrix:
  include:
    - d: dmd-nightly
    - d: dmd-2.091.1
  allow_failures:
    - d: dmd-nightly

script:
  - dub test --build=unittest-cov --compiler=${DC}
  - dub build --compiler=${DC}

after_success:
 - bash <(curl -s https://codecov.io/bash)
